name: hummm

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'feature/**'
    tags-ignore:
      - '**'

jobs:
  hummm:
    name: hummmm
    if: github.repository_owner == 'marcosbento'
    runs-on: ubuntu-latest

    container:

      image: marcosbento/ecflow:ubuntu_2404_amd64
      credentials:
        username: marcosbento
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    strategy:

      matrix:
        buildtype:
          - Debug
        preset:
          - linux.ubuntu.all.gcc13.release
          - linux.ubuntu.all.gcc14.release

    steps:

      - name: Checkout ecbuild
        uses: actions/checkout@v4
        with:
          repository: ecmwf/ecbuild
          path: ecbuild

      - name: Checkout ecflow
        uses: actions/checkout@v4
        with:
          path: ecflow

      - name: Configure
        run: |
          cd ecflow
          cmake --preset ${{ matrix.preset }}

      - name: Build
        run: |
          cd ecflow
          cmake --build --preset ${{ matrix.preset }}

      - name: Test
        run: |
          cd ecflow
          ctest --preset ${{ matrix.preset }} -L nighly