name: hummm

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'feature/**'
    tags-ignore:
      - '**'

jobs:
  hummm:
    name: hummmm
    runs-on: ubuntu-latest
    container:
      image: marcosbento/ecflow:ubuntu_2404
      credentials:
        username: marcosbento
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    strategy:
      matrix:
        profile:
          - gcc8
          - gcc13
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world! My profile is ${{ matrix.profile }}

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
