name: Sandbox

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'feature/**'
    tags-ignore:
      - '**'

jobs:
  sandbox:

    strategy:
      matrix:
        container:
          - ubuntu_2404_amd64
        preset:
          - linux.ubuntu.all.gcc13
          - linux.ubuntu.all.gcc14
        buildtype:
          - release

    name: ecFlow ${{ matrix.preset }}.${{ matrix.buildtype }} @ ${{ matrix.container }}
    if: github.repository_owner == 'marcosbento'
    runs-on: ubuntu-latest

    container:
      image: marcosbento/ecflow:${{ matrix.container }}
      credentials:
        username: marcosbento
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    steps:
      - name: Checkout ecbuild
        uses: actions/checkout@v4
        with:
          repository: ecmwf/ecbuild
          path: ecbuild

      - name: Checkout ecflow
        uses: actions/checkout@v4
        with:
          path: ecflow

      - name: Configure
        run: |
          cd ecflow
          cmake --preset ${{ matrix.preset }}.${{ matrix.buildtype }}

      - name: Build
        run: |
          cd ecflow
          cmake --build --preset ${{ matrix.preset }}.${{ matrix.buildtype }}

      - name: Test
        run: |
          cd ecflow
          ctest --preset ${{ matrix.preset }}.${{ matrix.buildtype }} -L nighly